# Generated by Django 2.0.5 on 2018-05-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180510_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='last_name',
        ),
    ]
