# Generated by Django 2.0.5 on 2018-05-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20180510_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
