# Generated by Django 2.0.5 on 2018-05-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20180511_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='is_staff',
            field=models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='is_superuser',
            field=models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0, verbose_name='是否超级用户'),
        ),
    ]
