# Generated by Django 2.0.5 on 2018-05-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20180511_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='is_active',
            field=models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0, verbose_name='是否激活账号'),
        ),
    ]
