# Generated by Django 2.0.5 on 2018-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180511_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='manager/%Y/%m', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='登录账号'),
        ),
    ]
