# Generated by Django 2.0.5 on 2018-05-11 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20180511_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
    ]
