# Generated by Django 2.0.5 on 2018-05-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180511_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='', verbose_name='照片'),
        ),
    ]
