# Generated by Django 2.0.5 on 2018-05-11 12:29

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20180511_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='manager/%Y/%m', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='work_description',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='职业描叙'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='工作内容'),
        ),
    ]
