# Generated by Django 2.0.5 on 2018-05-10 11:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expect_requirements', models.TextField(verbose_name='预期要求')),
                ('is_meet', models.IntegerField(choices=[(0, '未达到'), (1, '达到')], default=0, verbose_name='是否达到预期')),
                ('aspect', models.CharField(max_length=200, verbose_name='针对哪方面')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加记录时间')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
            ],
            options={
                'verbose_name': '员工评价信息',
                'verbose_name_plural': '员工评价信息',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='工资')),
                ('achievements', models.DecimalField(decimal_places=1, default=0, max_digits=1, verbose_name='绩效')),
                ('has_pay', models.IntegerField(default=0, verbose_name='是否结算工资')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加记录时间')),
            ],
            options={
                'verbose_name': '员工工资信息',
                'verbose_name_plural': '员工工资信息',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('image', models.ImageField(max_length=50, upload_to='', verbose_name='相片')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号码')),
                ('qq_number', models.CharField(max_length=11, verbose_name='QQ账号')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('house_addr', models.CharField(max_length=100, verbose_name='户籍地址')),
                ('card_number', models.CharField(max_length=20, verbose_name='身份证号码')),
                ('education', models.CharField(default='not', max_length=15, verbose_name='学历')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='毕业院校')),
                ('work_status', models.IntegerField(choices=[(0, '未入职'), (1, '入职'), (2, '离职')], default=0, verbose_name='在职状态')),
                ('join_time', models.DateTimeField(verbose_name='入职时间')),
                ('is_core', models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0, verbose_name='是否是核心成员')),
                ('is_charge', models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0, verbose_name='是否主负责人')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加记录时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department', verbose_name='所属部门')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Job', verbose_name='职位')),
            ],
            options={
                'verbose_name': '职工信息',
                'verbose_name_plural': '职工信息',
            },
        ),
        migrations.AddField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker', verbose_name='职工'),
        ),
        migrations.AddField(
            model_name='comment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Worker', verbose_name='员工'),
        ),
    ]
