# Generated by Django 2.0.5 on 2018-05-11 12:29

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='部门描叙'),
        ),
        migrations.AlterField(
            model_name='department',
            name='vision',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='部门愿景'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=DjangoUeditor.models.UEditorField(verbose_name='工作描叙'),
        ),
    ]
