# Generated by Django 2.0.5 on 2018-05-11 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评价人'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.Worker', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.Worker', verbose_name='职工'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.Department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.Job', verbose_name='职位'),
        ),
    ]
