# Generated by Django 2.0.5 on 2018-05-11 12:29

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20180511_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': '员工信息', 'verbose_name_plural': '员工信息'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=DjangoUeditor.models.UEditorField(verbose_name='评价内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='expect_requirements',
            field=DjangoUeditor.models.UEditorField(verbose_name='预期要求'),
        ),
    ]
