# Generated by Django 2.0.5 on 2018-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20180511_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='education',
            field=models.CharField(choices=[('not', '无学历'), ('highschool', '高中'), ('university', '本科'), ('graduate', '研究生'), ('doctorate', '博士')], default='not', max_length=15, verbose_name='学历'),
        ),
    ]
