# Generated by Django 2.0.5 on 2018-05-10 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门名')),
                ('duty', models.CharField(max_length=200, verbose_name='部门职责')),
                ('description', models.TextField(verbose_name='部门描叙')),
                ('create_time', models.DateField(verbose_name='创建时间')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='部门愿景')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加记录时间')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='职位名')),
                ('description', models.TextField(verbose_name='工作描叙')),
                ('expect_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预估工资')),
                ('is_core', models.IntegerField(choices=[(0, '不是'), (1, '是')], default=0, verbose_name='是否是核心职位')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加记录时间')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
            },
        ),
    ]
